---
title: "Exploring the UDBP Variable"
author: "Windy Wang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette:
  fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Exploring the UDBP Variable}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, echo = FALSE, message = FALSE, warning = FALSE)
library(dplyr)
devtools::load_all()
load_data(update = TRUE)
set_options()
# extrafont::loadfonts(device="win")

ds <- project_data
```


some notes:
fig.cap = "Your figure caption." 

The figure sizes have been customised so that you can easily put two images side-by-side. 
```{r, fig.show='hold'}
plot(1:10)
plot(10:1)
```

## Distribution
```{r histogram}
ds %>% 
  histo_plot(variable = "UDBP", 
             bin = 30, 
             xlab = "Urinary VDBP (ng/mL)",
             facet = TRUE)
```

Summary statistics
```{r}
ds %>% 
  filter(fVN == "Baseline") %>% 
  select(UDBP) %>% 
  summary()

ds %>% 
  filter(fVN == "3Year") %>% 
  select(UDBP) %>% 
  summary()

ds %>% 
  filter(fVN == "6Year") %>% 
  select(UDBP) %>% 
  summary()
```


## UDBP Progression

Convert UDBP long-data to wide

```{r long to wide}

ds_wide_udbp <- ds %>% 
  dplyr::select(SID, VN, UDBP) %>% 
  tidyr::spread(key = VN, value = UDBP, drop = TRUE, sep = ".") %>% 
  dplyr::rename(udbp1 = VN.1,
                udbp3 = VN.3,
                udbp6 = VN.6)

```

```{r boxplot}

ds %>% 
  box_plot(xvar="fVN",
           yvar="log(udbpCrRatio)",
           xlab="Visit Number",
           ylab="log Urinary VDBP (ng/mL)")
```

Growth curve of entire data
```{r growth curve}
ds %>% 
  dplyr::mutate(fSID = factor(SID)) %>%
  line_plot(xvar="fVN",
            yvar="UDBP",
            byvar="fSID",
            xlab="Visit Number",
            ylab="Urinary VDBP (ng/mL)")
```

Growth curve of progressors
```{r growth curve progress}

ds_UDBP_wide %>% 
  dplyr::filter(VN.3 > VN.1 | VN.6 > VN.1) %>% 
  dplyr::mutate(fSID = factor(SID)) %>% 
  line_plot(xvar = "VN",
            yvar = "UDBP",
            byvar = "fSID",
            xlab = "Visit Number",
            ylab = "Urinary VDBP")
  
```


Growth curve of regressors
```{r}

```


Growth curve of others (irregular)
```{r}

```


```{r latent curve mixed models}

```

