---
bibliography: path/to/bib/file
csl: path/to/bib/style/file
output: word_document
---

# Title page #

Title: Urinary Vitamin D Binding Protein Loss as a Potential Biomarker for Diabetic Nephropathy in Patients at Risk for Type 2 Diabetes

Author: Windy ZN Wang

Affiliations:

Disclaimers:

Correspondence:

Funding support:

# Abstract #

# Background #

# Subjects and Methods #

<!--
## Load data ##
-->

```{r setup, collapse=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
# Only set if the Rmd file is not in the parent directory (ie. 'projectname/')
knitr::opts_knit$set(root.dir = '../')
library(dplyr)
devtools::load_all()
load_data(update = TRUE)
set_options()
extrafont::loadfonts(device="win")
```

```{r loadData, message=FALSE}
# source('.Rprofile')
# run_setup()
# load_data('data/project_data.rda')
# dim(ds)
ds <- project_data
```

```{r caption_setup}
## Include captions below using `captioner` package
figNums <- captioner(prefix = 'Figure')
supFigNums <- captioner(prefix = 'Supplementary Figure')
tabNums <- captioner(prefix = 'Table')
supTabNums <- captioner(prefix = 'Supplementary Table')
```

# Results #

# Discussion #

## Acknowledgements ##

# References #
