---
title: 'Paper 2: Vitamin D'
author: "Windy Wang"
output: word_document
---

```{r setup, collapse=TRUE, echo=FALSE, message=FALSE, warning=FALSE}

# Only set if the Rmd file is not in the parent directory (ie. 'projectname/')
knitr::opts_knit$set(root.dir = '../')

knitr::opts_chunk$set(collapse = TRUE, echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
devtools::load_all()
load_data(update = TRUE)
set_options()
# extrafont::loadfonts(device="win")
```

```{r loadData, message=FALSE}

# source('.Rprofile')
# run_setup()
# load_data('data/project_data.rda')
# dim(ds)
ds <- project_data

dsBase <- ds %>% 
  dplyr::filter(fVN == "Baseline")

# Subjects with measurements at all visit numbers

dsComplete <- ds %>%
  dplyr::group_by(SID) %>%
  dplyr::filter(n() == 3) %>%
  dplyr::ungroup()

```

```{r caption_setup}

## Include captions below using `captioner` package

fig_nums <- captioner::captioner(prefix = 'Figure')
supfig_nums <- captioner::captioner(prefix = 'Supplementary Figure')
tab_nums <- captioner::captioner(prefix = 'Table')
suptab_nums <- captioner::captioner(prefix = 'Supplementary Table')
```

PAPER 2: VITAMIN D RESULTS
==========================

### Subject Characteristics

```{r subchar_vitd_baseline}

# Diet information is not available at baseline. Only VN 3 data is available at the present time.

tab_nums("subchar_vitd_baseline", "Subject characteristics across vitamin D status at baseline")

subchar_vitd_base <- tableone::CreateTableOne(
  vars = c("Age",
           "Sex",
           "Ethnicity",
           "BMI",
           "Waist",
           "eGFR",
           "ACR",
           "UrineCreatinine",
           "UrineMicroalbumin",
           "UrinaryCalcium",
           "UDBP",
           "udbpCrRatio",
           "VitaminD",
           "PTH",
           "MET",
           "Systolic",
           "Diastolic",
           "MeanArtPressure",
           "diet_milk",
           "diet_cal",
           "diet_supp_cal",
           "diet_supp_vitd",
           "OralContraceptive",
           "dmStatus"),
  strata = c("vitdStatus"),
  data = dsBase,
  factorVars = c("Sex", "Ethnicity", "OralContraceptive", "dmStatus")
) %>% 
  print(nonnormal = c("UDBP",
                      "ACR",
                      "UrineMicroalbumin"),
        quote = FALSE,
        noSpaces = TRUE) %>% 
  knitr::kable()
```

```{r subchar_vitd_time}

# Diet information is not available at baseline. Only VN 3 data is available at the present time.

tab_nums("subchar_vitd", "Subject characteristics across visit numbers")

subchar_vitd_base <- tableone::CreateTableOne(
  vars = c("Age",
           "Sex",
           "Ethnicity",
           "BMI",
           "Waist",
           "MET",
           "VitaminD",
           "PTH",
           "UDBP",
           "udbpCrRatio",
           "Systolic",
           "Diastolic",
           "MeanArtPressure",
           "OralContraceptive",
           "dmStatus"),
  strata = c("fVN"),
  data = ds,
  factorVars = c("Sex", "Ethnicity", "OralContraceptive", "dmStatus")
) %>% 
  print(nonnormal = c("UDBP",
                      "udbpCrRatio"),
        quote = FALSE,
        noSpaces = TRUE)
```

### Cross-Sectional

```{r vitd_boxplot}

# Clean data
vitd <- ds %>% 
  filter(fVN == "Baseline") %>% 
  select(vitdStatus, udbpCrRatio) %>%
  na.omit()

# Box plot of uVDBP in different albuminuria categories
vitd %>% 
  box_plot("vitdStatus", "log(udbpCrRatio)", 
            "Vitamin D Status",
            "log uVDBP:Creatinine")

# n
vitd %>% 
  group_by(vitdStatus) %>% 
  summarise(n = n())

# ANOVA
anova <- aov(formula = log(udbpCrRatio)~vitdStatus, data = vitd)
summary(anova)
TukeyHSD(anova)
rm(anova)
```


```{r vitd_scatterplot}

# Scatterplot of ACR and uVDBP ----------------------------------

dsBase %>% 
  scatter_plot("log(udbpCrRatio)", "VitaminD", 
               "log UDBP:Creatinine",
               "Serum 25(OH)D")

# Spearman Correlation ------------------------------------------

dsBase %>% 
  cor.test(formula = ~ VitaminD + udbpCrRatio, data = ., method = "spearman")

# Linear Regression ---------------------------------------------

dsBase %>% 
  prep_mason_data() %>% 
  mason_glm(y = "VitaminD",
            x = "logudbpCrRatio",
            covars = c("ageBase", "Sex", "Ethnicity", "BMI", "MET", "fDM")
            ) %>% 
  dplyr::filter(!term == "(Intercept)") %>%
  dplyr::mutate(p = round(p.value, 2),
    p = ifelse(p == "0", "<0.001", p),
    estCI = paste0(round(estimate, 2), " (",
                               round(conf.low, 2), ", ",
                               round(conf.high, 2), ")")) %>% 
  dplyr::select(Yterms, Xterms, term, estCI, p) %>% 
  # tidyr::spread(Yterms, estCI) %>%
  pander::pander()
  
```

#### Possible Effect Modifiers

```{r vitd_pth}

# Scatterplot

dsBase %>% 
  scatter_plot("PTH", "VitaminD", 
               "Parathyroid Hormone (pmol/L)",
               "Serum 25(OH)D (nmol/L)")

# Linear Regression ---------------------------------------------

dsBase %>% 
  prep_mason_data() %>% 
  mason_glm(y = "VitaminD",
            x = "PTH"
            ) %>% 
  dplyr::filter(!term == "(Intercept)") %>%
  dplyr::mutate(p = round(p.value, 2),
    p = ifelse(p == "0", "<0.001", p),
    estCI = paste0(round(estimate, 2), " (",
                               round(conf.low, 2), ", ",
                               round(conf.high, 2), ")")) %>% 
  dplyr::select(Yterms, Xterms, term, estCI, p) %>% 
  # tidyr::spread(Yterms, estCI) %>%
  pander::pander()
```

```{r vitd_season}

# Box plot of 25(OH)D in different seasons
dsBase %>% 
  box_plot("Season", "VitaminD", 
            "Seasons",
            "Serum 25(OH)D (nmol/L)")

# n
dsBase %>% 
  group_by(Season) %>% 
  summarise(n = n())

# ANOVA
anova <- aov(formula = VitaminD~Season, data = dsBase)
summary(anova)
TukeyHSD(anova)
rm(anova)
```


### Progression

```{r vitd_progression}

ds %>% 
  plot_progress(yvar = "VitaminD",
                ylab = "Serum 25(OH)D")

# Complete data

dsComplete %>% 
  plot_progress(yvar = "VitaminD",
                ylab = "Serum 25(OH)D")

# ANOVA ------------------------------------------------------------

anova <- aov(formula = VitaminD~fVN, data = dsComplete)
summary(anova)
TukeyHSD(anova)
rm(anova)
```

### Generalized Estimating Equations

```{r vitD_gee_baseline}

# Predictor is baseline UDBP ----------------------------------------

gee_vitd_baseline <- ds %>% 
  prep_mason_data_vitd() %>% 
  mason_gee(y = c("VitaminD", "PTH"),
            x = "udbpBase",
            covars = c("MonthsFromBaseline", "ageBase", "Sex", "Ethnicity", "MET", "BMI", "dmStatus", "Season"),
            intvar = "Season") %>% 
  mason::polish_renaming(rename_gee_vitd)

# GEE table ----------------------------------------------------------

gee_vitd_baseline %>% 
  gee_results_table() %>% 
  # tidyr::spread(Yterms, estCI) %>%
  pander::pander()

# Plot ---------------------------------------------------------------

gee_vitd_baseline <- ds %>% 
  prep_mason_data_vitd() %>% 
  mason_geeplot(y = c("VitaminD", "PTH"),
            x = "udbpBase",
            covars = c("MonthsFromBaseline", "ageBase", "Sex", 
                       "Ethnicity", "MET", "BMI", "dmStatus", "Season"),
            intvar = "Season") %>% 
  mason::polish_renaming(rename_gee_vitd)

plot_gee_results_vitd(gee_vitd_baseline,
                 yvars = c("Serum 25(OH)D (nmol/L)",
                           "PTH (pmol/L)"))

# Plot interaction ---------------------------------------------------

dsBase %>% 
  interac_plot(yvar = "PTH",
               intvar = "Season",
               ylab = "Parathyroid Hormone (pmol/L)") #Serum 25(OH)D (nmol/L) #Parathyroid Hormone (pmol/L)
```


```{r vitD_gee}

# Predictor is UDBP ----------------------------------------

gee_vitd <- ds %>% 
  prep_mason_data_vitd() %>% 
  mason_gee(y = c("VitaminD", "PTH"),
            x = "UDBP",
            covars = c("MonthsFromBaseline", "ageBase", "Sex", "Ethnicity", "MET", "BMI", "dmStatus", "Season"),
            intvar = "Season") %>% 
  mason::polish_renaming(rename_gee_vitd)

# GEE table ----------------------------------------------------------

gee_vitd %>% 
  dplyr::filter(!term == "(Intercept)") %>% 
  dplyr::mutate(p = round(p.value, 2),
    p = ifelse(p == "0", "<0.001", p),
    estCI = paste0(round(estimate, 2), " (",
                               round(conf.low, 2), ", ",
                               round(conf.high, 2), ")")) %>% 
  dplyr::select(Yterms, Xterms, term, estCI, p) %>% 
  # tidyr::spread(Yterms, estCI) %>%
  pander::pander()

# Plot ---------------------------------------------------------------

gee_vitd <- ds %>% 
  prep_mason_data_vitd() %>% 
  mason_geeplot(y = c("VitaminD", "PTH"),
            x = "UDBP",
            covars = c("MonthsFromBaseline", "ageBase", "Sex", "Ethnicity", "MET", "BMI", "dmStatus", "Season"),
            intvar = "Season") %>% 
  mason::polish_renaming(rename_gee_vitd)

plot_gee_results_vitd(gee_vitd,
                 yvars = c("Serum 25(OH)D (nmol/L)",
                           "PTH (pmol/L)"))

# Plot interaction ---------------------------------------------------

ds %>% 
  interac_plot(yvar = "VitaminD",
               intvar = "Season",
               ylab = "Serum 25(OH)D (nmol/L)")
```

